# Pandas

**Pandas** is a key Python library used for data cleaning, organization, and preparation before building machine learning models. 

FLOW: Pandas = NumPy + labels -- Series(1D + Index) -- DataFrame(2d table) -- creating from a dict -- numpy sits underneath

In [24]:
import pandas as pd
import numpy as np

# pd.DataFrame() - from a dictionary

restaraunt_data = {
    'Table No': [12, 14, 15],
    'Bill Amount': [1250, 890, 2400],
    'Waiter_Name': ['Shivansh', 'Awaneesh', 'Prity']
}

df = pd.DataFrame(restaraunt_data)

print(df)
print(type(df))
print(df['Bill Amount'])
print(type(df['Bill Amount']))

   Table No  Bill Amount Waiter_Name
0        12         1250    Shivansh
1        14          890    Awaneesh
2        15         2400       Prity
<class 'pandas.DataFrame'>
0    1250
1     890
2    2400
Name: Bill Amount, dtype: int64
<class 'pandas.Series'>

In [25]:
# pd.Series() - 1D Data with an index

total_bill = [4700, 8000, 1200, 500] 
s = pd.Series(total_bill, index=['Mon', 'Tue', 'Wed', 'Thur'])
print(s)
print(type(s))

Mon     4700
Tue     8000
Wed     1200
Thur     500
dtype: int64
<class 'pandas.Series'>

### Loading & Inspecting Data

In [27]:
df = pd.read_csv("tip 2.csv")

In [28]:
# df.head() - returns the first 5 rows of the dataframe
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
# df.sample() - returns a random sample of rows from the dataframe
df.sample(5)

     total_bill   tip   sex smoker   day    time  size
5         25.29  4.71  Male     No   Sun  Dinner     4
88        24.71  5.85  Male     No  Thur   Lunch     2
77        27.20  4.00  Male     No  Thur   Lunch     4
39        31.27  5.00  Male     No   Sat  Dinner     3
234       15.53  3.00  Male    Yes   Sat  Dinner     2

In [30]:
df.shape
print(df.columns)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [32]:
# df.info - returns a concise summary of the dataframe
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [33]:
# df.describe() - returns a statistical summary of the dataframe
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [37]:
# value_counts() - returns a series containing counts of unique values
# unique() - returns unique values of a series
# nunique() - returns the number of unique values in a series

print(df['day'].value_counts())  
print(df['day'].unique())        
print(df['day'].nunique())

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str
4

In [38]:
x = df['day']
print(x.shape)
y = df[['day']]
print(y.shape)

(244,)
(244, 1)